name: Docusaurus build 🦕

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  docusaurus_build_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Docusaurus build 🦕
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 0

      # - name: Setup Node.js 🔧
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      #     cache: 'yarn'

      - name: Setup bun 🔧
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Docusaurus build 🦕
        run: |
          pwd
          cd blog-website
          bun install --force
          DOCUSAURUS_SSR_CONCURRENCY=5 bun run build
